# https://taskfile.dev

version: "3"

vars:
  APP_NAME: markdown-code-runner

tasks:
  run:
    cmds:
      - go run ./... {{.CLI_ARGS}}
    silent: true

  build:
    sources:
      - '**/*.go'
    generates:
      - '{{.APP_NAME}}'
    cmds:
      - go get -u ./...
      - go mod tidy
      - task: format
      - task: check
      - go build
    # silent: true

  format:
    cmds:
      - go fmt ./...
      - task format:gofumpt
      - task format:golangci-lint

  format:gofumpt:
    desc: Run gofumpt if installed (https://github.com/mvdan/gofumpt)
    cmds:
      - |
        if command -v gofumpt >/dev/null 2>&1; then
          gofumpt -l -w .
        fi

  format:golangci-lint:
    desc: Run golangci-lint if installed (https://golangci-lint.run)
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint fmt
        fi

  check:
    cmds:
      - go vet ./...
      - task: check:gofumpt
      - task: check:golangci-lint
    # silent: true

  check:gofumpt:
    desc: Run gofumpt if installed (https://github.com/mvdan/gofumpt)
    cmds:
      - |
        if command -v gofumpt >/dev/null 2>&1; then
          gofumpt -l .
        fi

  check:golangci-lint:
    desc: Run golangci-lint if installed (https://golangci-lint.run)
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint run
        fi

  test:
    deps:
      - build
    cmds:
      - go test -v ./...
    # silent: true

  dev:coding-standards:check:
    cmds:
      - task: dev:coding-standards:apply
      - docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint '**/*.md'

  dev:coding-standards:apply:
    cmds:
      - docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint '**/*.md' --fix

  release:create:
    prompt: Create release {{.CLI_ARGS}}?
    cmds:
      - gh itkdev changelog --release {{ .CLI_ARGS }} --base main
      - sed -i'' -E 's/(const version = ")[^"]+(")/\1{{.CLI_ARGS}}\2/' cmd/root.go
      - git diff
      - task: build
      - git add -- cmd/root.go
    preconditions:
      - sh: |
          git diff --diff-filter=ACMRT --exit-code
        msg: changes detected
      - sh: |
          [[ "{{.CLI_ARGS}}" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]
        msg: invalid or missing version ({{.CLI_ARGS}}). Call with `-- v*.*.*`
      - sh: |
          [ ! $(git tag -l "{{.CLI_ARGS}}") ]
        msg: |
          tag {{.CLI_ARGS}} already exists

  # Used only for testing interactive shell and color output
  test:interactive:
    prompt: "Do you relly want to run this task?"
    cmds:
      - echo "Ok, task run …"
