on:
  push:
    tags:
      - 'v*.*.*'

name: Publish

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Get the tag
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      run: |
        echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_ENV"

    - name: Set version
      run: |
        sed -i 's/const version = ".*"/const version="'$GIT_TAG'"/' cmd/root.go

    - name: Commit and push changes
      # https://github.com/devops-infra/action-commit-push
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        amend: true

    - name: Publish
      # https://go.dev/doc/modules/publishing
      run: |
        GOPROXY=proxy.golang.org go list -m "github.com/mikkelricky/markdown-code-runner@$GIT_TAG"
